
name: hello-team-13
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  my-job:
    runs-on: ubuntu-22.04
    steps:
      - name: helloStep
        run: echo "Hello The JSONs!"
